include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    unawaited_futures: true
    prefer_final_fields: true
    prefer_single_quotes: true
    use_super_parameters: true